version: "3"

services:
  qtcreator-swine-z3:
    image: qtcreator-swine-z3:latest
    container_name: qtcreator-swine-z3
    security_opt: [seccomp:unconfined]
    cap_add: [SYS_PTRACE]
    build:
      context: .
      dockerfile: qtcreator.Dockerfile
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ..:/swine-z3
    network_mode: host
