# Creates a docker container where the LoAT root direcotry is mounted to /LoAT
# and triggers a build.

version: "3"

services:
  swine-z3-build:
    image: swine-z3-build:latest
    container_name: swine-z3-build
    security_opt: [seccomp:unconfined]
    cap_add: [SYS_PTRACE]
    volumes:
      - ..:/swine-z3
    build:
      context: .
      dockerfile: build.Dockerfile
    network_mode: host
