name: Build SwInE for all platforms

on:

  # Also allow this action to be triggered manually via a button in
  # the GitHub UI.
  workflow_dispatch:

jobs:
  build-linux:
    uses: ./.github/workflows/build-linux.yml
  build-linux-static:
    uses: ./.github/workflows/build-linux-static.yml
  build-osx:
    uses: ./.github/workflows/build-osx.yml
  build-windows:
    uses: ./.github/workflows/build-windows.yml
