name: Build SwInE Windows

on:

  # Also allow this action to be triggered manually via a button in
  # the GitHub UI.
  workflow_dispatch:

  workflow_call:

jobs:
  build-binary:
    runs-on: windows-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: robinraju/release-downloader@v1
        with:
          repository: 'Z3Prover/z3'
          tag: z3-4.13.4
          fileName:  z3-4.13.4-x64-win.zip
          out-file-path: 'z3'
          extract: true
      - run: |
          mkdir -p ./build
          mkdir -p ./include
          mv ./z3/z3-4.13.4-x64-win/bin/libz3.lib ./build/
          mv ./z3/z3-4.13.4-x64-win/include/* ./include/
        shell: bash

      - name: Install boost
        uses: MarkusJx/install-boost@v2
        id: install-boost
        with:
          boost_version: 1.87.0
          toolset: msvc

      - run: |
          export INCLUDE=$INCLUDE:"${{github.workspace}}\include"
          export PATH=$PATH:"${{github.workspace}}\build"
          test() {
            ret=`./Release/swine-z3 ../examples/ex0.smt2`
            echo $ret
            if [[ $ret != sat* ]]
            then
                return 1
            fi
          }
          mv ./boost/boost/lib/* ./build/
          mv ./boost/boost/include/boost/boost ./include/boost/
          cd ./build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build . --config Release
          cd ..
          test
        shell: bash

      - name: Export SwInE Binary
        uses: actions/upload-artifact@master
        with:
          name: swine-z3-windows-${{ github.ref_name }}
          path: |
            ${{github.workspace}}\build\swine-z3
            ${{github.workspace}}\build\libswine-z3.dll

